---
# Configuration file for MegaLinter
#
# See all available variables at https://megalinter.io/latest/config-file/ and in
# linters documentation

# all, none, or list of linter keys
APPLY_FIXES: none

# If you use ENABLE variable, all other languages/formats/tooling-formats will
# be disabled by default
# ENABLE:

# If you use ENABLE_LINTERS variable, all other linters will be disabled by
# default
# ENABLE_LINTERS:

# TODO put these back once things are under control.
DISABLE:
  - COPYPASTE
  - SPELL
  - PYTHON
  - JAVASCRIPT # it is all generated (and do not know how to ignore generated)

# TODO investigate why these are failing.
DISABLE_LINTERS:
  - PYTHON_PYLINT # many "Unable to import" errors.
  - REPOSITORY_DEVSKIM # "Failed to parse Data at the root level is invalid. Line 1, position 1. as a XML document: null"
  - CSHARP_ROSLYNATOR # "Could not load file or assembly 'System.Composition.AttributedModel..."
  - PROTOBUF_PROTOLINT # FIXME very unhappy with field names etc.

EXCLUDED_DIRECTORIES:
  - "Might be useful"
  - "megalinter-reports"

SHOW_ELAPSED_TIME: true

# GitLeaks: only scan the files in this commit, not the entire history
# TODO review previous failures and add to .gitleaksignore
REPOSITORY_GITLEAKS_ARGUMENTS: "--no-git"

# use recommended config file https://stylelint.io/user-guide/configure/
CSS_STYLELINT_CONFIG_FILE: stylelint.config.js

# only fail the run on higher priority stuff.
REPOSITORY_KICS_ARGUMENTS: "--fail-on critical,high"

# these checks are also done by kics (where they are lower priority):
# CKV_DOCKER_2: "Ensure that HEALTHCHECK instructions have been added to container images"
# CKV_DOCKER_3: "Ensure that a user for the container has been created"
# CKV_DOCKER_7: "Ensure the base image uses a non latest version tag"
REPOSITORY_CHECKOV_ARGUMENTS: "--skip-check CKV_DOCKER_2,CKV_DOCKER_3,CKV_DOCKER_7"

# these checks are also done by kics (where they are lower priority):
# DL3007 using :latest
DOCKERFILE_HADOLINT_ARGUMENTS: "--ignore DL3007"

# only fail the run on higher priority stuff.
REPOSITORY_TRIVY_ARGUMENTS: "--severity HIGH,CRITICAL"
