FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY . .
RUN dotnet restore "MediaFeeder.Web/MediaFeeder.Web.csproj"
WORKDIR "/src/MediaFeeder.Web"
RUN dotnet build "MediaFeeder.Web.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "MediaFeeder.Web.csproj" -c Release -o /app/publish

FROM lipanski/docker-static-website:latest as final
COPY --from=publish /app/publish/wwwroot .
