FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG TARGETARCH
WORKDIR /source

# Copy project file and restore as distinct layers
COPY --link . .
RUN dotnet restore "MediaFeeder.Web/MediaFeeder.Web.csproj" -a $TARGETARCH

# Copy source code and publish app
RUN dotnet publish -a $TARGETARCH "MediaFeeder.Web/MediaFeeder.Web.csproj" --no-restore -o /app -c Debug

# Runtime stage
FROM nginx:alpine AS final
WORKDIR /usr/share/nginx/html

COPY nginx.conf /etc/nginx/nginx.conf
# Copy from Environment(build/publish)
COPY --from=build /app/wwwroot .

EXPOSE 80
USER $APP_UID
