FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG TARGETARCH
WORKDIR /source

# Copy project file and restore as distinct layers
COPY --link . .
RUN dotnet restore "MediaFeeder.Web/MediaFeeder.Web.csproj" -a $TARGETARCH

# Copy source code and publish app
RUN dotnet publish -a $TARGETARCH "MediaFeeder.Web.csproj" --no-restore -o /app

# Runtime stage
FROM mcr.microsoft.com/dotnet/aspnet:8.0
EXPOSE 8080
WORKDIR /app
COPY --link --from=build /app .
USER $APP_UID
ENTRYPOINT ["dotnet", "MediaFeeder.Web.dll"]
